"""empty message

Revision ID: 8a4d3ef76f03
Revises: 9bd3fcccd632
Create Date: 2019-08-31 18:44:43.105469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4d3ef76f03'
down_revision = '9bd3fcccd632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.Column('todo', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studylog')
    # ### end Alembic commands ###
